@port = 443
@host = https://89.168.61.130:{{port}}



#################### ITEMS #####################

GET {{host}}/api/items



#################### CATEGORIES #####################


GET {{host}}/api/categories

###
GET {{host}}/api/categories/Education

