@port = 3000
@host = http://localhost:{{port}}



#################### ITEMS #####################

GET {{host}}/api/items



#################### CATEGORIES #####################


GET {{host}}/api/categories

###
GET {{host}}/api/categories/Education

